# Generated by Django 6.0.2 on 2026-03-19 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='make',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='vehicleimage',
            old_name='image_url',
            new_name='image',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('MUV', 'MUV'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Pickup', 'Pickup')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_cc',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='km_driven',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_power',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_type',
            field=models.CharField(default='1st Owner', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seating_capacity',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='torque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='variant',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Sold', 'Sold'), ('Pending', 'Pending')], default='Active', max_length=10),
        ),
    ]
