# Generated by Django 6.0.2 on 2026-03-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_rename_make_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
