# Generated by Django 6.0.2 on 2026-03-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicle_options_vehicle_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
