# Generated by Django 6.0.2 on 2026-03-25 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_vehicle_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='inspector',
        ),
    ]
