# Generated by Django 6.0.2 on 2026-04-14 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_payment_currency_payment_user_alter_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vehicle.vehicle'),
        ),
    ]
