# Generated by Django 6.0.2 on 2026-04-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_offer_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='seller',
        ),
    ]
